### ISSUE TITLE
数据库为空

### ISSUE THREAD

**Issue by lympassion** [Forest75/ExamOnline#1]
你好，这个项目里用的是MySQL，我连接上我的MySQL5.7.32，创建了一个exam_system数据库，也运行了`py manage.py migrate`。但当我启动django服务后，进入登陆，但我不知道登录用户以及密码，查看exam_system，提示为空，这个数据库是要本地自己重新建立吗？

**Comment by Forestjylee** [comment]
你好，我重新尝试部署了一下，在django==2.1.1的情况下是可以运行的，不知道是否是新版django写法有所改变的原因，你可以尝试一下安装低版本的django。在migrate之前需要手动创建数据库，数据库的名称可以在settings.py文件中指定，创建完成之后运行migrate会创建自动创建数据表。创建数据表完成之后使用python manage.py createsuperuser创建管理员账户，然后启动django服务，浏览器访问/admin后台页面，用管理员账户登录进去之后就可以通过后台操作数据表了。通常情况下可以先在用户表创建一个老师账户，然后使用老师账户在/login页面登陆系统，就可以通过上传excel文件批量导入学生。Excel文件只要有姓名、学号、班级三列即可，批量创建的学生账号的密码默认为学号的后六位。之后的操作都可以在老师|学生页面完成。

**Comment by lympassion** [comment]
蟹蟹，我用的django==3.0.7，刚才应该是没有创建管理员账户的，现在好了
